### ISSUE TITLE
Notes and walls stop spawnig mid-song / walls not appearing in correct orientations

### ISSUE THREAD

**Issue by zoli4911** [Aeroluna/Heck#29] opened 2022-04-03 20:27 UTC
**Describe the bug**
Hello, I've been waiting for updates of NoodleExtensions and Chroma for BS 1.21 , today I happily saw they are available, so I installed them and tried out a bunch of songs.
At first everything semmed to work good, but later when I re-played a couple songs I liked, I noticed that on certain levels, the notes and any other items just stopped spawning after a while, only the music and light effects were going on.

Another thing I noticed that on many levels, the structures build of walls are all out of the place, non recognizable, seems the elements are not displaying in the correct orientation. On other cases, big walls are covering the whole middle of the play area for really long periods, where the notes are coming. Not sure what these maps should look like when normal, but certainly doesn't seem right as is.

**To Reproduce**
Here are 2 levels which worked good at first, then items stopped spawning later, mid-song. 
https://beatsaver.com/maps/228ba
https://beatsaver.com/maps/1f6ea

**Expected behavior**
Notes and walls should spawn correctly throughout the whole map.

**Additional context**
please see log here (updated): https://drive.google.com/file/d/1NHOkMwkp5_R85dvN8aLvBlBz-ab3gSy_/view?usp=sharing

**Comment by Aeroluna** [comment] 2022-04-03 20:47
The link to your log does not work.

**Comment by zoli4911** [comment] 2022-04-03 20:51
Sorry. Does it work like this?
https://drive.google.com/file/d/1NHOkMwkp5_R85dvN8aLvBlBz-ab3gSy_/view?usp=sharing

**Comment by zoli4911** [comment] 2022-04-06 17:46
Hi, Thank you for the quick fix!
It partially solved the issue. Notes and walls are now spawning consistently through the whole level, but the orientation and position of wall elements is still off sometimes. Not sure what it depends on, sometimes when I launch the game, all songs play fine, but other times lots of levels with special walls are affected.

Another thing happened ocassionally, that walls were displaying in correct position, but the texture seemed to be shifted, the edge outlines seemed to be on the sides, making crosses.

New log:
https://drive.google.com/file/d/1eVq9TnYG_o19hmXPNBBbgVe1ixXM0gDa/view?usp=sharing

This is a level heavily affected:
https://beatsaver.com/maps/d7fa
for example the lines on the road are high thin walls in the center.

Could you please re-check?

And thank you for the amazing work!

**Comment by SilberComic** [comment] 2022-04-07 15:31
i noticed this in ANALYS and NULCTRL ( https://beatsaver.com/maps/d00c ; https://beatsaver.com/maps/ed2a ) aswell, the walls are creating a huge mess and staying too long sometimes and that results in not being able to play some maps

**Comment by Aeroluna** [comment] 2022-04-08 01:14
In the future, create separate issues for each issue. I'm not able to reproduce the issue, please list any modfiers/player options/settings that you used.

**Comment by zoli4911** [comment] 2022-04-08 08:18
Sorry, will open a new issue next time. The problems didn't occured to me yesterday, but I will gather and list all my settings next time it occurs. Seems to be randomly appearing, or at least I havent found the trigger yet.

**Comment by Aeroluna** [comment] 2022-04-21 03:16
Resolved in Mapping Extensions https://github.com/Kylemc1413/MappingExtensions/commit/caefbf0e5ff4ecd94ea9c6baa353f0780b746d36

**Closed by Aeroluna** 2022-04-21 03:16 UTC
Labels: type: bug, status: confirmed, mod: noodle extensions
