### ISSUE TITLE
Environment not quite right

### ISSUE THREAD

**Issue by Lilobast** [Aeroluna/Heck#39] opened 2022-05-02 08:23 UTC
Environment don't look like what it should on certain maps

Problem appears on the map Shelter for example : https://beatsaver.com/maps/1ad55

[_latest.log](https://github.com/Aeroluna/Heck/files/8601641/_latest.log)

Note: tried on Chroma 2.5.11 & 2.5.12

**Comment by TzurS11** [comment] 2022-05-02 08:27
For this map blame me.
this map is not future proof so things break.
ima work on a fix soon maybe...

**Comment by Lilobast** [comment] 2022-05-02 08:46
ooh ok
I also have issues on other maps but according to the logs it's heck related
Should I open a new issue for this?

**Comment by Lilobast** [comment] 2022-05-02 19:35
oooh and also in the latest version of Heck / Chroma / Noodle extension (1.3.7, 2.5.12 & 1.4.10) player don't follow the notes anymore

**Comment by Aeroluna** [comment] 2022-05-04 02:24
"Environment don't look like what it should on certain maps" is not very descriptive.
Seeing as TszurS11 is taking the blame, I will close this issue, please open separate issues for other bugs (with more information please).

**Closed by Aeroluna** 2022-05-04 02:24 UTC
Labels: type: bug, status: can't reproduce, mod: chroma

**Comment by pcnorden** [comment] 2022-05-04 18:12
I actually had the same problem on the same song and I've found out that it's due to some issue with MappingExtensions that is right now released on ModAssistant. I would put this up as a duplicate of issue #38 due to both issues that I had were solved by compiling and using the current github version of the MappingExtensions mod.
After MappingExtensions mod gets updated to 1.7.2 the Shelter map will work flawlessly again 😄 

And to actually give some context as to what "don't look like what it should on certain maps" actually looks like, it looks like the image below when it should be reading "Shelter".
![vlcsnap-2022-05-04-19h36m35s147](https://user-images.githubusercontent.com/7767295/166746595-baee6456-eae4-484d-991d-98caa7ed5b61.png)

***
### Incase you wanna compile MappingExtensions to solve your issues

Be forewarned though: to compile MappingExtensions you need:
* Visual Studio
* .NET Framework 4.8
* Adding a enviroment variable called `BeatSaberDir` and point the variable to the Beat Saber folder. In my case it's `D:\SteamGamesFolder\steamapps\common\Beat Saber`

After you have all of that, you can just download the mappingextensions mod from github as a zip file and unzip it somewhere.

Next up you need to head into the folder called `MappingExtensions` inside the extracted `MappingExtensions` folder and open `MappingExtensions.csproj` in a ordinary text editor.

In the XML file that shows up, you need to change at the very top where you can see
```XML
<PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <TreatWarningAsErrors>true</TreatWarningsAsErrors>
</PropertyGroup>
```
you need to change
```XML
<LangVersion>latest</LangVersion>
```
into
```XML
<LangVersion>preview</LangVersion>
```
Save and close the file and now head back to the main MappingExtensions folder and open the `MappingExtensions.sln` file with Visual Studio.

After visual studio has loaded up the project, you can click on the "Debug" dropdown menu up in the left-hand side of this screenshot and select "Release" which after that is selected, you right-click `MappingExtensions` as shown in the right-hand side of the below screenshot, and in the menu that shows up you press "Rebuild".
![image](https://user-images.githubusercontent.com/7767295/166751106-a0f50720-bcf9-485d-ae3e-60871df9888a.png)

Visual studio should now have some text showing in the bottom of the screen and something that says "1 build succeeded" or something alike.

I would like to attach my already compiled version of MappingExtensions, but nobody sane would use the file due to safety concerns 🤣 I'm also unsure of what the license allows me to do

**Comment by Meivyn** [comment] 2022-05-04 18:34
You can remove the compile section, ME has been approved on Mod Assistant right now.

**Comment by pcnorden** [comment] 2022-05-04 18:38
Well now I feel bad for writing all of that out and posting unecessary information, but thank you very much for pointing that out. I've removed the information on how to compile the mod from scratch now.

Thanks for letting me know and hope you'll have a wonderful day 😄
