### ISSUE TITLE
Settings Setter causes a softlock in the middle of a song selection menu fade animation on 1.29.1

### ISSUE THREAD

**Issue by TheBlackParrot** [Aeroluna/Heck#86] opened 2023-05-04 12:56 UTC
**Describe the bug**
In 1.29.1, the game will softlock after finishing 2 maps that ask to change settings. The Settings Setter menu is barely visible, and the song selection menu is slightly more transparent than normal.
1.29.1 simulates the full back button animation after pressing either Accept or Decline. In 1.28, the song selection menu instantly snaps back.

**To Reproduce**
1. Play any 2 maps that ask to change settings
2. Accept or decline the changes each time
3. Softlock

**Expected behavior**
Not a softlock

**Additional context**
[2023.05.04.08.22.25.log](https://github.com/Aeroluna/Heck/files/11397678/2023.05.04.08.22.25.log)

**Comment by Aeroluna** [comment] 2023-05-04 17:56
This is caused by an incompatibility with GottaGoFast, this is fixed in https://github.com/Aeroluna/Heck/commit/2c0dc3db83b32d0604b0c08e8679a1ae0c48f74d and will be included with the next upload

**Closed by Aeroluna** 2023-05-04 17:56 UTC
Labels: type: bug, status: confirmed, mod: heck

**Comment by TheBlackParrot** [comment] 2023-07-21 20:51
Any update on this? There's been no updates to the mod on BeatMods for 1.29.1, but 1.31 is receiving updates.

**Comment by Aeroluna** [comment] 2023-07-21 21:07
The fix is implemented in the 1.31 release, uploads for older game versions do not get approved on beatmods so it is not possible for me to backport the fix.
